### ISSUE TITLE
capturing crashes in M code

### ISSUE THREAD

**Issue by psimon2** [jewuma/mumps-debug#21] opened 2023-08-24 08:48 UTC
Hi,

Great plugin - been looking for something like this for a while now.
If you are debugging a routine and it crashes, then the UI does not stop the debugging process or display an error (as far as I can see) - apologies if that is not the case.
Also, MDEBUG crashes - which means you need to start it up again

Many Thanks,
-- Paul.

**Comment by jewuma** [comment] 2023-08-24 13:38
Can you provide an example? Normally the debugger stops at the position of an error and you can restart the program.

**Comment by psimon2** [comment] 2023-08-24 14:30
Thanks for getting back to me

YDB>D ^MDEBUG
Debugger connected
Error occurred: 150373850,PSTEST+3^PSTEST,%YDB-E-LVUNDEF, Undefined local variable: B

PSTEST ; ; 8/23/23 3:12pm
	K ^BOB
	; CRASH
	S A=B
	d test
	;S A=B
	S A="TEST"
	D STT
	quit
STT ;
	D A
	D B
	quit
	;	
A ;
	W !,"A"
	S ^BOB(1)=""
	QUIT
B ;
	W !,"B"
	S ^BOB(2)=""
	QUIT
	;
test ;
	s f="/tmp/test.txt"
	close f
	open f:(readonly)
	f  u f r str q:$zeof  do
	. u 0 w !,str
	. quit
	close f
	quit

MDEBUG version:
  MDEBUG     ;Debugging Routine for GT.M/YottaDB by Jens Wulf
2           ;Version 0.9.4
3           ;2023-04-24
4           ;License: LGPL
5           ;Usage on your own Risk - No guaranties

**Comment by psimon2** [comment] 2023-08-24 14:32
Sorry, MDEBUG crashes then must hang - returning to linux prompt?

YDB>d ^MDEBUG
Debugger connected
Error occurred: 150373850,PSTEST+3^PSTEST,%YDB-E-LVUNDEF, Undefined local variable: B
root@DESKTOP-LJRBQ0F:/opt/yotta#

**Comment by jewuma** [comment] 2023-08-24 16:25
I can't reproduce it here. Can you post your launch.json and maybe the values of the ydb* env-variables?
Where is vs-code running on, on the same machine as yottadb runs on or on a windows machine?

**Comment by psimon2** [comment] 2023-08-24 17:32
Everything is running on my laptop (windows 10)
Yotta is running in WSL-2
Same crash happens when running in an Oracle VM
Yotta version is r1.38
GTM:  GT.M V6.3-014 Linux x86_64

Windows Subsystem for Linux is now available in the Microsoft Store!
You can upgrade by running 'wsl.exe --update' or by visiting https://aka.ms/wslstorepage
Installing WSL from the Microsoft Store will give you the latest WSL updates, faster.
For more information please visit https://aka.ms/wslstoreinfo

paul@DESKTOP-LJRBQ0F:~$

export ydb_dist=/opt/yotta
export ydb_gbldir=/root/.yottadb/r1.38_x86_64/g/yottadb.gld
export ydb_dir=/root/.yottadb
export ydb_rel=r1.38_x86_64

$ydb_dist/mupip SET -NULL_SUBSCRIPTS=true -region DEFAULT
$ydb_dist/mupip set - journal=off -region '*'
$ydb_dist/mupip set -access_method=mm -region DEFAULT

I have yotta running in an AWS environment - but I'll need to get someone to open port 9000 in order to do some testing

Why don't to send me a version of MDEBUG that sets an audit global in various places - that might give us a indication of what's going on?

I'm away now until the 2nd Sept. though - hope the above gives you the information you need?

Thanks,
-- Paul.

**Comment by psimon2** [comment] 2023-08-24 17:32
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "mumps",
            "request": "launch",
            "name": "Active File",
            "program": "${file}",
            "hostname": "172.22.145.98",
            "port": 9000,
            "localRoutinesPath": "C:\\\\TEMP\\\\",
            "stopOnEntry": true
        }
    ]
}

**Comment by jewuma** [comment] 2023-08-27 17:27
I've tested two scenarios:
1. VS Code runs on a windows machine and you're editing routines via samba-share. Like this:  
smb.conf: 
[routines]
        comment = Mumps routines
        path = /var/lib/yottadb/r
        read only = No
\\linux-machine\routines is mapped to X:\ on my windows-machine.

Then the  launch.json looks like this:   {
      "type": "mumps",
      "request": "launch",
      "name": "Debug active File",
      "program": "${file}",
      "stopOnEntry": true,
      "hostname": "192.168.178.105",
      "localRoutinesPath": "X:/",
      "port": 9000
    }
2. VS Code and yotta runs on a linux machine:

{
      "type": "mumps",
      "request": "launch",
      "name": "Debug active File",
      "program": "${file}",
      "stopOnEntry": true,
      "hostname": "192.168.178.105",
      "localRoutinesPath": "/var/lib/yottadb/r",
      "port": 9000
    }

I wonder why you have no ydb_routines env-variable. It looks like this on my side:
ydb_routines=/var/lib/yottadb/o(/var/lib/yottadb/r) /usr/local/lib/yottadb/r130/

Also Error-Handling is done by my extension if $ZTRAP="B" which is default. Please check this too.

**Comment by psimon2** [comment] 2023-09-04 13:01
Hi -
Is there any chance that we can set up a call to talk about your plug-in and the issues that we have found.
We are really impressed by what you have developed so far.
Many Thanks,
-- Paul.

**Comment by jewuma** [comment] 2023-09-04 13:15
Well, I'd try my best, but my english is not that fluent and I don't know if I can help you, if my previous answers didn't help.
Maybe we give this thread one more try before we do a zoom-meeting or something similar.
Did you have a look at my suggestions?

**Comment by psimon2** [comment] 2023-09-04 13:49
If I show you what's happening on zoom - then you'll be able to get a much better understanding of my set up etc.
When are you free for a call?
Yes, I did look at your suggestions - but unfortunately they did not help, but I do have a possible fix that we can discuss:
WAIT(%ZPOS)      ;Wait for next Command from Editor
52       N %DEV,%IO,%CMD,%CMDS,%CMDLINE,%SOCKET,%I,%VAR,%MI
53       **S $ET="G RESET^MDEBUG"**

Please don't worry about the language barrier

There's also a new yotta forum that contains plenty of expertise - that you might want to join?
https://discord.com/channels/1137126843774931055/

This is where I found out about your plugin

Thanks,
-- Paul.

**Comment by psimon2** [comment] 2023-09-05 11:23
I've made some progress with this - and setting $ET to $ZSTEP seems to have solved the problem:

WAIT(%ZPOS)   			;Wait for next Command from Editor
	N %DEV,%IO,%CMD,%CMDS,%CMDLINE,%SOCKET,%I,%VAR,%MI
	;possible Debugger-Commands
	S %CMDS="START;QUIT;EXIT;INTO;OUTOF;OVER;CONTINUE;SETBP;VARS;INTERNALS;CLEARBP;REQUESTBP;RESET;GETVAR;ERRCHK;RESTART"
	S %IO=$I
	S %DEV=^%MDEBUG($J,"DEV"),%SOCKET=^%MDEBUG($J,"SOCKET")
	U %DEV:(SOCKET=%SOCKET:DELIM=$C(10):EXCEPTION="HALT")
	S:$ZTRAP="B" $ZTRAP=$ZSTEP	;Error-Handling by Debugger if not set by Debuggee
	;S $ET="G RESET^MDEBUG"
	S $ET=$ZSTEP

The yotta documentation also talks about handling errors:

[Choosing $ETRAP or $ZTRAP](https://docs.yottadb.com/ProgrammersGuide/errproc.html#id20)[¶](https://docs.yottadb.com/ProgrammersGuide/errproc.html#choosing-etrap-or-ztrap)
Making a choice between the two mechanisms for error handling is mostly a matter of compatibility. If compatibility with existing YottaDB code is important, and that code happens to use $ZTRAP, then $ZTRAP is the best effort choice. If compatibility with code written in M dialects from other vendors is important, then $ETRAP or a non-default form of $ZTRAP probably is the better choice.

When no pre-existing code exists that favors one mechanism, the features of the mechanisms themselves should be examined.

Almost any effect that can be achieved using one mechanism can also be achieved using the other. However, some effects are easier to achieve using one method, and some are easier using with the other.

If the mechanisms are mixed, or there is a desire to refer to $ECODE in an environment using $ZTRAP, it is recommended to have $ZTRAP error code SET $ECODE=”” at some appropriate time, so that $ECODE does not become cluttered with errors that have been successfully handled.

If you are up for meeting up with us, then that would be great

Thanks,
-- Paul.

**Comment by jewuma** [comment] 2023-09-05 13:48
Hello Paul,
nice to hear, that you succeded with $ETRAP. In my environment $ZTRAP is used to handle upcoming Errors and I tested with $ZT beacause of that. If $ET is used in your case please remember that a possible Error-Handling-Routine is out of order if you set $ET unconditionally in ^MDEBUG.
if you still want to meet via zoom or teams, a possible time could be tomorrow  (06.09.2023) at 5pm CEST.
Regards
Jens

**Comment by psimon2** [comment] 2023-09-05 13:55
Hi Jens,

I don't seem to be able to find your email address on github
Please email me using psimon1@supanet.com so that we can set up a meeting

Many Thanks,
-- Paul.

**Comment by jewuma** [comment] 2023-09-27 12:09
The problem should be fixed with version 1.1.9

**Closed as completed by jewuma** 2023-09-27 12:09 UTC
